### ISSUE TITLE
empty table!!

### ISSUE THREAD

**Issue by EliasSalom** [Fullstack-Alfanar/react-hw2-Amal#3]
I have been checking your deployment and I found that every table is empty!!
the task asks to 

1. put some data inside the table
2. validate every input

**you need to finish these 2 tasks !!**

**Comment by AmalShalabi** [comment]
Hello Elias,
again the problem here, that though I set it to do updating automatically after you confirm the merge to main...
**BUT AGAIN! IT DOES NOT!** 
so I had setted "manually" and now you have the risible results.
please check it again and enjoy! :)

Amal

**Comment by EliasSalom** [comment]
yes, filling the data is working now, but there is a lot of problems in the console!!
**please fix them !!**

**Comment by AmalShalabi** [comment]
had solved all the errors

**Comment by EliasSalom** [comment]
@AmalShalabi No, the problem still there please open the console and try to work with your system and you will see that's there is a lot of error,

**Comment by AmalShalabi** [comment]
Hey Elias,
Again I had to update it manually ,
You can see the result without errors in console.
enjoy ! :)
